import mongoose from 'mongoose';
import Achievement from '../models/Achievement.js';
import { getUserById } from './authService.js';
import { getUserAnalytics } from './analyticsService.js';
import Quiz from '../models/Quiz.js';
import { devMemoryQuizzes, devMemoryAttempts, isMongoConnected } from './quizService.js';
import logger from '../utils/logger.js';

// In-memory fallback for development when MongoDB is unreachable
export const devMemoryAchievements = new Map();

/**
 * 10 Core Achievement Badges Registry
 */
export const BADGE_REGISTRY = [
  {
    id: 'FIRST_STEP',
    title: 'First Step',
    description: 'Complete your first quiz attempt',
    tier: 'bronze',
    icon: 'Footprints',
  },
  {
    id: 'STREAK_3',
    title: 'On Fire',
    description: 'Maintain a 3-day active streak',
    tier: 'silver',
    icon: 'Flame',
  },
  {
    id: 'STREAK_7',
    title: 'Unstoppable',
    description: 'Reach a 7-day streak milestone',
    tier: 'gold',
    icon: 'Zap',
  },
  {
    id: 'PERFECT_SCORE',
    title: 'Perfectionist',
    description: 'Score 100% on any quiz',
    tier: 'gold',
    icon: 'Award',
  },
  {
    id: 'SPEED_DEMON',
    title: 'Speed Demon',
    description: 'Complete a quiz in under 2 minutes with >= 80% accuracy',
    tier: 'silver',
    icon: 'Timer',
  },
  {
    id: 'XP_HUNTER',
    title: 'XP Hunter',
    description: 'Accumulate 500+ total XP',
    tier: 'bronze',
    icon: 'Sparkles',
  },
  {
    id: 'CENTURION',
    title: 'Centurion',
    description: 'Reach 1,000+ total XP',
    tier: 'gold',
    icon: 'Crown',
  },
  {
    id: 'MASTER_ARCHITECT',
    title: 'Master Architect',
    description: 'Create or AI-generate a custom quiz',
    tier: 'silver',
    icon: 'Wand2',
  },
  {
    id: 'POLYGLOT',
    title: 'Topic Explorer',
    description: 'Pass quizzes across 3 or more distinct topics',
    tier: 'platinum',
    icon: 'Globe',
  },
  {
    id: 'AI_SCHOLAR',
    title: 'AI Scholar',
    description: 'Complete a quiz generated by AI or from document notes',
    tier: 'bronze',
    icon: 'Brain',
  },
];

/**
 * Helper to fetch unlocked badges for a user
 */
const getUnlockedMap = async (userId) => {
  const idStr = String(userId);
  const map = new Map();

  if (isMongoConnected()) {
    try {
      const records = await Achievement.find({ userId }).lean();
      for (const rec of records) {
        map.set(rec.badgeId, rec);
      }
    } catch (err) {
      logger.warn(`Failed to read achievements from MongoDB: ${err.message}`);
    }
  }

  // Check in-memory store
  const userMem = devMemoryAchievements.get(idStr);
  if (userMem) {
    for (const [bId, data] of userMem.entries()) {
      if (!map.has(bId)) {
        map.set(bId, data);
      }
    }
  }

  return map;
};

/**
 * Save an unlocked badge to DB or in-memory
 */
const saveAchievement = async (userId, badgeDef, metadata = {}) => {
  const idStr = String(userId);
  const now = new Date();

  const record = {
    userId,
    badgeId: badgeDef.id,
    tier: badgeDef.tier,
    unlockedAt: now,
    metadata,
  };

  if (isMongoConnected()) {
    try {
      await Achievement.findOneAndUpdate(
        { userId, badgeId: badgeDef.id },
        { $setOnInsert: record },
        { upsert: true, new: true }
      );
    } catch (err) {
      logger.warn(`Failed to save achievement to MongoDB: ${err.message}`);
    }
  }

  // Update in-memory store
  if (!devMemoryAchievements.has(idStr)) {
    devMemoryAchievements.set(idStr, new Map());
  }
  devMemoryAchievements.get(idStr).set(badgeDef.id, record);

  logger.success(`🏆 User [${idStr}] unlocked achievement "${badgeDef.title}" (${badgeDef.tier.toUpperCase()})`);
  return record;
};

/**
 * Evaluate and award achievements for a user
 * Returns array of newly unlocked badges
 */
export const evaluateUserAchievements = async (userId, context = {}) => {
  if (!userId) return [];
  const idStr = String(userId);

  const [user, analytics, unlockedMap] = await Promise.all([
    getUserById(userId),
    getUserAnalytics(userId),
    getUnlockedMap(userId),
  ]);

  if (!user) return [];

  const newlyUnlocked = [];
  const summary = analytics.summary || {};
  const recentAttempts = analytics.recentAttempts || [];
  const totalAttempts = summary.totalAttempts || 0;
  const userXp = user.xp || 0;
  const userStreak = user.streak || 0;

  // Compute stats for conditions
  const maxScore = recentAttempts.reduce((max, a) => Math.max(max, a.percentage || 0), 0);
  const has100Percent = recentAttempts.some((a) => a.percentage === 100);
  const hasSpeedRun = recentAttempts.some(
    (a) => a.percentage >= 80 && a.timeSpentSeconds > 0 && a.timeSpentSeconds <= 120
  );

  // Distinct passed topics
  const passedTopics = new Set();
  recentAttempts.forEach((a) => {
    if (a.passed && a.quizTopic) {
      passedTopics.add(a.quizTopic.toLowerCase().trim());
    }
  });

  // Created quizzes count
  let createdCount = 0;
  if (isMongoConnected()) {
    try {
      createdCount = await Quiz.countDocuments({ userId });
    } catch (e) {
      // ignore
    }
  }
  if (createdCount === 0) {
    createdCount = Array.from(devMemoryQuizzes.values()).filter((q) => String(q.userId) === idStr).length;
  }

  // Has taken AI or PDF quiz
  const hasTakenAI = recentAttempts.some((a) => a.sourceType === 'ai' || a.sourceType === 'pdf');

  // Evaluate each badge in the registry
  for (const badge of BADGE_REGISTRY) {
    if (unlockedMap.has(badge.id)) continue; // Already unlocked

    let shouldUnlock = false;
    let meta = {};

    switch (badge.id) {
      case 'FIRST_STEP':
        if (totalAttempts >= 1) {
          shouldUnlock = true;
          meta = { totalAttempts };
        }
        break;

      case 'STREAK_3':
        if (userStreak >= 3) {
          shouldUnlock = true;
          meta = { streak: userStreak };
        }
        break;

      case 'STREAK_7':
        if (userStreak >= 7) {
          shouldUnlock = true;
          meta = { streak: userStreak };
        }
        break;

      case 'PERFECT_SCORE':
        if (has100Percent) {
          shouldUnlock = true;
          meta = { percentage: 100 };
        }
        break;

      case 'SPEED_DEMON':
        if (hasSpeedRun) {
          shouldUnlock = true;
          meta = { speedRun: true };
        }
        break;

      case 'XP_HUNTER':
        if (userXp >= 500) {
          shouldUnlock = true;
          meta = { xp: userXp };
        }
        break;

      case 'CENTURION':
        if (userXp >= 1000) {
          shouldUnlock = true;
          meta = { xp: userXp };
        }
        break;

      case 'MASTER_ARCHITECT':
        if (createdCount >= 1 || context.quizCreated) {
          shouldUnlock = true;
          meta = { createdCount };
        }
        break;

      case 'POLYGLOT':
        if (passedTopics.size >= 3) {
          shouldUnlock = true;
          meta = { topics: Array.from(passedTopics) };
        }
        break;

      case 'AI_SCHOLAR':
        if (hasTakenAI || context.usedAI) {
          shouldUnlock = true;
          meta = { aiEngagement: true };
        }
        break;

      default:
        break;
    }

    if (shouldUnlock) {
      const saved = await saveAchievement(userId, badge, meta);
      newlyUnlocked.push({
        ...badge,
        unlockedAt: saved.unlockedAt,
      });
    }
  }

  return newlyUnlocked;
};

/**
 * Get all badges with unlock status and progress for a user
 */
export const getUserAchievements = async (userId) => {
  const [user, analytics, unlockedMap] = await Promise.all([
    getUserById(userId),
    getUserAnalytics(userId),
    getUnlockedMap(userId),
  ]);

  const summary = analytics.summary || {};
  const recentAttempts = analytics.recentAttempts || [];
  const totalAttempts = summary.totalAttempts || 0;
  const userXp = user?.xp || 0;
  const userStreak = user?.streak || 0;

  const maxScore = recentAttempts.reduce((max, a) => Math.max(max, a.percentage || 0), 0);
  const hasSpeedRun = recentAttempts.some(
    (a) => a.percentage >= 80 && a.timeSpentSeconds > 0 && a.timeSpentSeconds <= 120
  );

  const passedTopics = new Set();
  recentAttempts.forEach((a) => {
    if (a.passed && a.quizTopic) passedTopics.add(a.quizTopic.toLowerCase().trim());
  });

  const hasTakenAI = recentAttempts.some((a) => a.sourceType === 'ai' || a.sourceType === 'pdf');

  let createdCount = 0;
  if (isMongoConnected()) {
    try {
      createdCount = await Quiz.countDocuments({ userId });
    } catch (e) {
      // ignore
    }
  }
  if (createdCount === 0) {
    createdCount = Array.from(devMemoryQuizzes.values()).filter((q) => String(q.userId) === String(userId)).length;
  }

  const results = BADGE_REGISTRY.map((badge) => {
    const isUnlocked = unlockedMap.has(badge.id);
    const unlockedRecord = unlockedMap.get(badge.id);

    let progress = 0;
    let progressLabel = '';

    switch (badge.id) {
      case 'FIRST_STEP':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((totalAttempts / 1) * 100));
        progressLabel = `${Math.min(1, totalAttempts)} / 1 Quiz`;
        break;

      case 'STREAK_3':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((userStreak / 3) * 100));
        progressLabel = `${userStreak} / 3 Days`;
        break;

      case 'STREAK_7':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((userStreak / 7) * 100));
        progressLabel = `${userStreak} / 7 Days`;
        break;

      case 'PERFECT_SCORE':
        progress = isUnlocked ? 100 : Math.round(maxScore);
        progressLabel = `${Math.round(maxScore)}% / 100%`;
        break;

      case 'SPEED_DEMON':
        progress = isUnlocked ? 100 : hasSpeedRun ? 100 : (summary.quizzesPassed > 0 ? 50 : 0);
        progressLabel = isUnlocked || hasSpeedRun ? 'Completed' : 'Under 2 mins (>80%)';
        break;

      case 'XP_HUNTER':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((userXp / 500) * 100));
        progressLabel = `${userXp} / 500 XP`;
        break;

      case 'CENTURION':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((userXp / 1000) * 100));
        progressLabel = `${userXp} / 1,000 XP`;
        break;

      case 'MASTER_ARCHITECT':
        progress = isUnlocked ? 100 : (createdCount >= 1 ? 100 : 0);
        progressLabel = `${createdCount} / 1 Created`;
        break;

      case 'POLYGLOT':
        progress = isUnlocked ? 100 : Math.min(100, Math.round((passedTopics.size / 3) * 100));
        progressLabel = `${passedTopics.size} / 3 Topics`;
        break;

      case 'AI_SCHOLAR':
        progress = isUnlocked ? 100 : hasTakenAI ? 100 : 0;
        progressLabel = isUnlocked || hasTakenAI ? 'Completed' : '0 / 1 AI Quiz';
        break;

      default:
        progress = isUnlocked ? 100 : 0;
        progressLabel = isUnlocked ? 'Unlocked' : 'Locked';
        break;
    }

    return {
      ...badge,
      unlocked: isUnlocked,
      unlockedAt: unlockedRecord?.unlockedAt || null,
      progress,
      progressLabel,
    };
  });

  const totalUnlocked = results.filter((b) => b.unlocked).length;

  return {
    totalBadges: BADGE_REGISTRY.length,
    unlockedCount: totalUnlocked,
    completionPercentage: Math.round((totalUnlocked / BADGE_REGISTRY.length) * 100),
    badges: results,
  };
};

export default {
  BADGE_REGISTRY,
  getUserAchievements,
  evaluateUserAchievements,
};
