/**
 * Quiz Export & Printable Document Utilities
 * Generates formatted Markdown, JSON, and printable HTML exam papers.
 * Strictly 100% Pure JavaScript (ESM)
 */

/**
 * Triggers client-side browser file download from string content
 */
export const downloadBlob = (content, filename, mimeType = 'text/plain;charset=utf-8') => {
  if (typeof window === 'undefined') return;

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();

  setTimeout(() => {
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, 100);
};

/**
 * Formats a quiz into clean, readable Markdown (.md)
 */
export const exportQuizToMarkdown = (quiz, { includeAnswers = true } = {}) => {
  if (!quiz) return '';

  const safeTitle = quiz.title || 'Untitled Quiz';
  const topic = quiz.topic || 'General';
  const difficulty = (quiz.difficulty || 'medium').toUpperCase();
  const timeLimit = quiz.timeLimit ? `${quiz.timeLimit} minutes` : 'Untimed';
  const questions = quiz.questions || [];

  let md = `# 📝 ${safeTitle}\n\n`;
  md += `> **Topic:** ${topic} | **Difficulty:** ${difficulty} | **Time Limit:** ${timeLimit} | **Total Questions:** ${questions.length}\n\n`;

  if (quiz.description) {
    md += `${quiz.description}\n\n`;
  }

  md += `---\n\n## Questions\n\n`;

  questions.forEach((q, idx) => {
    const qNum = idx + 1;
    md += `### ${qNum}. ${q.question}\n\n`;

    const options = q.options || [];
    const correctIdx = Number(q.correctAnswer);

    options.forEach((opt, oIdx) => {
      const optLetter = String.fromCharCode(65 + oIdx);
      if (includeAnswers && oIdx === correctIdx) {
        md += `- [x] **(${optLetter})** ${opt} *(Correct Answer)*\n`;
      } else {
        md += `- [ ] **(${optLetter})** ${opt}\n`;
      }
    });

    if (includeAnswers && q.explanation) {
      md += `\n<details>\n<summary>💡 Explanation & Concept Breakdown</summary>\n\n${q.explanation}\n</details>\n`;
    }

    md += `\n`;
  });

  if (includeAnswers) {
    md += `---\n\n## 🔑 Answer Key\n\n| Question | Correct Option | Answer Text |\n|:---:|:---:|:---|\n`;
    questions.forEach((q, idx) => {
      const correctIdx = Number(q.correctAnswer);
      const letter = String.fromCharCode(65 + correctIdx);
      const text = q.options?.[correctIdx] || '';
      md += `| ${idx + 1} | **${letter}** | ${text} |\n`;
    });
    md += `\n`;
  }

  md += `---\n*Generated by Quizora AI Platform*\n`;
  return md;
};

/**
 * Serializes a quiz into portable JSON
 */
export const exportQuizToJSON = (quiz) => {
  if (!quiz) return '{}';

  const exportPayload = {
    title: quiz.title,
    description: quiz.description,
    topic: quiz.topic,
    difficulty: quiz.difficulty,
    timeLimit: quiz.timeLimit,
    sourceType: quiz.sourceType,
    exportedAt: new Date().toISOString(),
    questions: (quiz.questions || []).map((q) => ({
      question: q.question,
      options: q.options,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation,
    })),
  };

  return JSON.stringify(exportPayload, null, 2);
};

/**
 * Opens a dedicated printable HTML test paper for physical printing or "Save as PDF"
 */
export const printQuizExam = (quiz, { includeAnswerKey = false } = {}) => {
  if (typeof window === 'undefined' || !quiz) return;

  const printWindow = window.open('', '_blank', 'width=900,height=800');
  if (!printWindow) {
    alert('Please allow popups for this site to open the printable exam sheet.');
    return;
  }

  const safeTitle = quiz.title || 'Examination Assessment';
  const topic = (quiz.topic || 'General').toUpperCase();
  const difficulty = (quiz.difficulty || 'medium').toUpperCase();
  const timeLimit = quiz.timeLimit ? `${quiz.timeLimit} Minutes` : 'Untimed';
  const questions = quiz.questions || [];

  const questionsHtml = questions
    .map((q, idx) => {
      const qNum = idx + 1;
      const optionsHtml = (q.options || [])
        .map((opt, oIdx) => {
          const letter = String.fromCharCode(65 + oIdx);
          return `
            <div class="option-row">
              <span class="bubble"></span>
              <span class="letter">(${letter})</span>
              <span class="option-text">${escapeHtml(opt)}</span>
            </div>
          `;
        })
        .join('');

      return `
        <div class="question-block">
          <div class="question-header">
            <span class="question-num">${qNum}.</span>
            <div class="question-title">${escapeHtml(q.question)}</div>
          </div>
          <div class="options-container">
            ${optionsHtml}
          </div>
        </div>
      `;
    })
    .join('');

  const answerKeyHtml = includeAnswerKey
    ? `
      <div class="page-break"></div>
      <div class="answer-key-section">
        <h2 class="answer-key-title">🔑 Answer Key & Scoring Guide</h2>
        <table class="key-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Key</th>
              <th>Correct Option</th>
              <th>Explanation Summary</th>
            </tr>
          </thead>
          <tbody>
            ${questions
              .map((q, idx) => {
                const correctIdx = Number(q.correctAnswer);
                const letter = String.fromCharCode(65 + correctIdx);
                const text = q.options?.[correctIdx] || '';
                const expl = q.explanation || 'Direct curriculum standard.';
                return `
                <tr>
                  <td><strong>${idx + 1}</strong></td>
                  <td><span class="key-badge">${letter}</span></td>
                  <td>${escapeHtml(text)}</td>
                  <td class="expl-text">${escapeHtml(expl)}</td>
                </tr>
              `;
              })
              .join('')}
          </tbody>
        </table>
      </div>
    `
    : '';

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <title>${escapeHtml(safeTitle)} - Printable Exam</title>
      <style>
        @page {
          size: A4 portrait;
          margin: 18mm 16mm;
        }
        * {
          box-sizing: border-box;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          color: #0f172a;
          background: #ffffff;
          margin: 0;
          padding: 24px;
          line-height: 1.5;
        }
        .exam-header {
          border-bottom: 2px solid #0f172a;
          padding-bottom: 12px;
          margin-bottom: 20px;
        }
        .header-top {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          margin-bottom: 8px;
        }
        .exam-title {
          font-size: 22px;
          font-weight: 800;
          color: #0f172a;
          margin: 0;
        }
        .exam-badges {
          font-size: 11px;
          font-weight: 700;
          color: #475569;
          text-transform: uppercase;
        }
        .header-meta {
          display: grid;
          grid-template-columns: 1fr 1fr 1fr;
          gap: 12px;
          margin-top: 14px;
          padding: 10px 14px;
          border: 1px solid #cbd5e1;
          border-radius: 6px;
          background: #f8fafc;
          font-size: 13px;
        }
        .student-fields {
          display: grid;
          grid-template-columns: 1.5fr 1fr 1fr;
          gap: 16px;
          margin-top: 14px;
          font-size: 13px;
        }
        .field-line {
          border-bottom: 1px solid #475569;
          min-height: 20px;
        }
        .field-label {
          font-weight: 600;
          color: #334155;
          margin-bottom: 4px;
        }
        .instructions {
          margin: 16px 0 24px 0;
          padding: 10px 14px;
          background: #f1f5f9;
          border-left: 4px solid #6366f1;
          font-size: 12px;
          color: #334155;
        }
        .question-block {
          margin-bottom: 20px;
          page-break-inside: avoid;
        }
        .question-header {
          display: flex;
          gap: 8px;
          margin-bottom: 10px;
        }
        .question-num {
          font-weight: 800;
          font-size: 15px;
          color: #0f172a;
        }
        .question-title {
          font-weight: 600;
          font-size: 15px;
          color: #0f172a;
        }
        .options-container {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 8px 16px;
          padding-left: 20px;
        }
        .option-row {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 13px;
          color: #1e293b;
        }
        .bubble {
          width: 14px;
          height: 14px;
          border: 1.5px solid #64748b;
          border-radius: 50%;
          display: inline-block;
          flex-shrink: 0;
        }
        .letter {
          font-weight: 700;
          color: #475569;
        }
        .option-text {
          word-break: break-word;
        }
        .page-break {
          page-break-before: always;
        }
        .answer-key-section {
          margin-top: 30px;
        }
        .answer-key-title {
          font-size: 18px;
          font-weight: 800;
          color: #0f172a;
          border-bottom: 2px solid #6366f1;
          padding-bottom: 6px;
          margin-bottom: 16px;
        }
        .key-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 12px;
        }
        .key-table th, .key-table td {
          border: 1px solid #cbd5e1;
          padding: 8px 10px;
          text-align: left;
        }
        .key-table th {
          background: #f1f5f9;
          font-weight: 700;
        }
        .key-badge {
          display: inline-block;
          padding: 2px 8px;
          background: #6366f1;
          color: #ffffff;
          border-radius: 4px;
          font-weight: 800;
          font-size: 11px;
        }
        .expl-text {
          color: #475569;
        }
        @media screen {
          body {
            max-width: 820px;
            margin: 20px auto;
            border: 1px solid #e2e8f0;
            box-shadow: 0 10px 25px rgba(0,0,0,0.08);
            border-radius: 12px;
          }
          .no-print-bar {
            position: sticky;
            top: 0;
            background: #0f172a;
            color: #ffffff;
            padding: 12px 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-top-left-radius: 12px;
            border-top-right-radius: 12px;
            z-index: 100;
          }
          .print-btn {
            background: #6366f1;
            color: #ffffff;
            border: none;
            padding: 8px 16px;
            font-size: 14px;
            font-weight: 600;
            border-radius: 6px;
            cursor: pointer;
          }
        }
        @media print {
          .no-print-bar {
            display: none !important;
          }
          body {
            padding: 0 !important;
            margin: 0 !important;
            border: none !important;
            box-shadow: none !important;
          }
        }
      </style>
    </head>
    <body>
      <div class="no-print-bar">
        <span>📄 Printable Exam Sheet Ready</span>
        <button class="print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
      </div>

      <div class="exam-header">
        <div class="header-top">
          <h1 class="exam-title">${escapeHtml(safeTitle)}</h1>
          <span class="exam-badges">${escapeHtml(topic)} &bull; ${escapeHtml(difficulty)}</span>
        </div>

        <div class="header-meta">
          <div><strong>Assessment:</strong> ${questions.length} Questions</div>
          <div><strong>Time Allotted:</strong> ${escapeHtml(timeLimit)}</div>
          <div><strong>Passing Grade:</strong> 70%</div>
        </div>

        <div class="student-fields">
          <div>
            <div class="field-label">Student Name:</div>
            <div class="field-line"></div>
          </div>
          <div>
            <div class="field-label">Date:</div>
            <div class="field-line"></div>
          </div>
          <div>
            <div class="field-label">Score / Grade:</div>
            <div class="field-line"></div>
          </div>
        </div>
      </div>

      <div class="instructions">
        <strong>Directions:</strong> Select the best response for each multiple choice question by filling in the corresponding circle completely. Mark only one option per question.
      </div>

      <div class="exam-body">
        ${questionsHtml}
      </div>

      ${answerKeyHtml}

      <script>
        // Automatically open system print dialog after DOM render
        window.addEventListener('load', () => {
          setTimeout(() => {
            window.print();
          }, 300);
        });
      </script>
    </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
};

/**
 * Escapes HTML entities to prevent XSS during print preview rendering
 */
function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

const exportUtils = {
  downloadBlob,
  exportQuizToMarkdown,
  exportQuizToJSON,
  printQuizExam,
};

export default exportUtils;
